name: lab3-workflow
run-name: ${{ github.actor }} is  deploying a new model
on: [push]
jobs:
  deploy-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy model
        run: ./.github/workflows/deploy.sh
        shell: bash
      - uses: stefanzweifel/git-auto-commit-action@v4